### ISSUE TITLE
CFP: Add a public view to display submission in "Open call" state

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1066]
Related: 
https://github.com/OpenTechFund/opentech.fund/issues/1065

**Comment by frjo** [comment]
@Parbhat Can you take this on? If possible I would like to have a Wagtail "Open Call index page" that list all submissions in the new "com_open_call" state (see OPEN_CALL_PHASES in workflow.py).

This index page the editors can then add an introduction text to (like most other index pages) and place where they want to.

~~~~
ApplicationSubmission.objects.filter(status__in=OPEN_CALL_PHASES)
~~~~

I have merged in PR  #1123 and #1127 to master already.

See also related #1065 that is also assigned to you now.

**Comment by Parbhat** [comment]
@frjo Working on it. So, that's why we created a feature to group form fields. If form submission on a Community Prototype Fund (CPF) select *Help me find someone to implement it!* then it will be open call submission. And it will be displayed on Open Call Index page and others can click *build it* for showing interest of actual submission.

**Comment by frjo** [comment]
@Parbhat Exactly.

OTF will first look at it and if they like it set them to status "Open call". Then they get displayed on this view with the "Build it" button from #1065.

**Comment by Parbhat** [comment]
@frjo Great.
