### ISSUE TITLE
Reviewer Consensus are not displayed accurately

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1129]
This issue is related to #985

Reviewer Consensus are not displayed accurately. Agreement with a review is not counted as completed. Reviewer consensus are displayed as two "1's" under the 'Reviews Assgn. Comp.' category even though consensus have been reached. 

Here is one example, but there are several: https://apply.opentech.fund/apply/submissions/3863/

Original text from the functional spec winter sprint report states: "Agreement with a review will be counted as a completed review."

Fixes #1151

**Comment by frjo** [comment]
It's in the Submission list view at "/apply/submissions/" that the bug shows up. On the detailed view it looks fine.

The "Reviews Assgn. Comp." are for this submission showing 1/1 when it should show 2/2.

**Comment by fourthletter** [comment]
![image](https://user-images.githubusercontent.com/20019656/56718380-ecccf880-673e-11e9-9925-01d9e8ece77d.png)

**Comment by todd-dembrey** [comment]
@fourthletter @frjo Is this fixed by the changes in #1151?

**Comment by frjo** [comment]
Yes, I believe this fixes #1151.

**Comment by gibbsmaya** [comment]
#1151 fixes this issue, however there are performance issues so the remaining work on this issue is to revisit the approach to achieve the same result without performance implications.

The issue and associated acceptance criteria are captured by the initial issue #985. Closing this issue in favour of that one.
