### ISSUE TITLE
Reviewer ordering: detailed view

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#1192]
Correct reviewer ordering is:

```
<role reviews submitted ordered by role order>
<staff reviews submitted>
<role not reviewed ordered by role order>
<staff not reviewed>
---
<external reviews>
<external not reviewed>
```

(Submission View currently correct)

**Acceptance criteria**

 - [x] Detailed view (e.g. https://apply.opentech.fund/apply/rounds/823/?submission=3912) ordered as per correct sort order

**Comment by abigail-hampson** [comment]
Issue:
Went into this submission (which had no reviewers assigned), added myself as primary and Chris as secondary reviewer. Reviewers got added but other reviewers and reviews are now displaying. This has happened on multiple submissions. 
https://dev-apply.opentech.fund/apply/submissions/10/
![Screen Shot 2019-05-09 at 10 53 33](https://user-images.githubusercontent.com/43568191/57446093-c6817f80-724b-11e9-9401-1d888df6d1de.png)

Otherwise ordering looks good, can be deployed to test

**Comment by todd-dembrey** [comment]
This is because you are testing on a concept note, their is no external review involved here so we do not show them. A proposals would be a good one to test the external reviewers.

**Comment by fourthletter** [comment]
Features are functional during test. Thanks! 💥

I tested applications in Community Lab and reviewers "Abigail" and "Di" are sequential in every view, i.e., list, detailed, and submission. https://test-apply.opentech.fund/apply/rounds/736/
