### ISSUE TITLE
As a manager/reviewer, easy way to view all reviews I've (or another user) has completed

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#342]

**Comment by gibbsmaya** [comment]
Historic reviews by me is planned to be covered in the work we are doing in the Winter 2019 Sprints. Adding to project board.

May need to split out a separate issue for being able to see what other people have reviewed. this should currently be searchable within the main submission listings but only by assigned reviewers rather than completed reviews.

**Comment by fourthletter** [comment]
1) Reviewer is a filter option, 2) Manager could read every review written about a particular submission on a single screen.

**Comment by danblah** [comment]
Agree, can close this
