### ISSUE TITLE
Create a notification in the team channel when a user's role has been changed (added/removed)

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#526]

**Comment by frjo** [comment]
No easy way to see what has changed on a user account but it will now send out a notice whenever a user account is edited and it has roles. The notice list the roles.

**Comment by fourthletter** [comment]
@frjo Tack!

1) This issue addresses these business cases below? Are there others? 
2) Who has authority to change these roles? 

[] Staff replaced as the "Lead" of a Round
[] A user receives notification when they are added/removed as primary reviewer role, AC role, Partner role, etc.

**Comment by frjo** [comment]
@fourthletter  Roles in this context are the groups you set on user accounts to give them different privileges. The groups/roles that are in use now are "Community reviewer", "Partner", "Reviewer" and "Staff". (Drupal calls them "roles" but wagtail uses the term "groups". Dan and I got stuck on calling in roles I believe, I also think that is a better term for this in general.)

This issue is regarding changes to these roles/groups on user accounts.

Lead and primary/secondary reviewer are something you are assigned per round/submission. If the current notifications for them are not as you want them please make a new issue for that.

**Comment by danblah** [comment]
Works as expected. please commit.
