### ISSUE TITLE
https://www.opentech.fund/reimbursement/ is a broken link

### ISSUE THREAD

**Issue by becklm** [OpenTechFund/opentech.fund#535]

**Comment by dmcdev1** [comment]
@frjo adding https://www.opentech.fund/stipend/ to this ticket. In the interim, can you confirm whether the following pages are still operational and ok to use? cc @danblah 
- https://old.opentech.fund/reimbursement/
- https://old.opentech.fund/stipend/

**Comment by frjo** [comment]
@becklm What current page should it go to? Or is the page missing completely?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by frjo** [comment]
Please use https://archive.opentech.fund/ instead of https://old.opentech.fund/. They go to the same site but "archive" is the correct one to use.

This seems to be webforms and that functionality is not in place on the new site so feel free to use the old ones for now. That site will work until OTF decides otherwise.

**Comment by dmcdev1** [comment]
Got it @fredrik. In that case I've set redirects for /reimbursement and /stipend to https://archive.opentech.fund/reimbursement/ and https://archive.opentech.fund/stipend/ so they should now work cc @becklm
