### ISSUE TITLE
A way to to clear filters/search on submission overview

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#584]
it's not easily apparent that you're viewing search results or how to "undo" the search filter.

**Comment by frjo** [comment]
On or more filter will say "2 of 10 nnn selected", is that not apparent?

To reset simply click the "Submission" menu item again.

Since there are only a handful of people using this view I think it should be easy to point this out to them.

A more importen issue for this view in my opinion is that it's getting really slow. Working on fixing that.

**Comment by danblah** [comment]
I think ideally, within each filter, there was an uncheck all or check all

**Comment by gibbsmaya** [comment]
We are revisiting how the filters are represented. This is planned to be covered in the work we are doing in the Winter 2019 Sprints. Adding to project board.

@tmsndrs FYI to take into your design of the new filters/search.
