### ISSUE TITLE
We need an additional workflow available, a 1-stage application with external review, for things like Labs and Rapid Response, who have AC review requirements 

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#650]
Right now only the 2-stage application workflow allows external review for the 2nd application. We have a 1-stage application (for RFP's) but it doesn't allow external review.

**Comment by todd-dembrey** [comment]
@frjo The current request workflow should be copied, renamed and for use with labs. Unique names are important for all stages except first, just adding `lab_` should be sufficient. You should then just need to add in the extra stage for the `requests`

The next stage of this is making sure that we change the open labs to the new workflow (manually) and change the workflow and status of open lab applications to the new names. This will be a little fiddly (due to the lock on the status field).

**Comment by frjo** [comment]
I have a PR for this here 
https://github.com/OpenTechFund/opentech.fund/pull/652

Will need an ok from @todd-dembrey before I deploy it. Most likely will need some work.

**Comment by frjo** [comment]
@danblah Todd might have time tomorrow afternoon to look at this. He is schduled to work with OTF on Thursday and Friday next week so at the latest this will get fixed then.

The affected submissions all belong to RRFund-2018? When the new workflow is in place that round and all the existing submissions under it need to be converted to the new workflow?

**Comment by todd-dembrey** [comment]
I think the changes in #652 are fine. I've fixed the failing tests.
