### ISSUE TITLE
Design: filters and search

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#779]
Design and behaviour of filters and search when expanded. Currently design just shows icon to click to access filters and search.

**Comment by tmsndrs** [comment]
**Behaviours**
- When a user searches the page reloads to show related results. In the future we would like to make this a live search. 
- When a user clicks filter, filter options appear
- Once a filter is applied filter button changes to clear filters so that live filters can't be hidden and can only be cleared
- User should be able to filter search results or search filtered results
- Search field retains the input value the user has provided after search is applied 
- From the main (all) submissions page filtering and search will move users to a single filtered list of submissions 

**Design** 
- Filter boxes have had their heigh reduced by 8 pixels from the current design
