### ISSUE TITLE
Applicant Friendly Statuses

### ISSUE THREAD

**Issue by todd-dembrey** [OpenTechFund/opentech.fund#818]
Implement the changes from the review of #786 

**Acceptance criteria**
- [x] Applicant sees the user friendly status on the status bar
- [x] Applicant sees the transition message for their statuses in activity feed
- [x] Applicants don't get emailed about transitions they cannot see 
- [x] Applicant doesn't see notifications for changes where they cannot see the target phase (No change too status in #786) 
- [x] OTF staff sees OTF transition messages within the messages in activity feed

Design:
![image](https://user-images.githubusercontent.com/6338661/50835431-98983700-134e-11e9-8858-82fdac678217.png)

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by todd-dembrey** [comment]
Blocked waiting on a discussion with @tmsndrs

**Comment by todd-dembrey** [comment]
This is in #838 ready for review and deployed to develop.

**Comment by todd-dembrey** [comment]
@gibbsmaya which application were you testing with?

**Comment by gibbsmaya** [comment]
@todd-dembrey https://dev-apply.opentech.fund/apply/submissions/13/ and https://dev-apply.opentech.fund/apply/submissions/14/

**Comment by todd-dembrey** [comment]
I have pushed a fix for applicant messages not displaying. 

There are some Screening messages showing which i think were from when we weren't setting visibility correctly and are unrelated to the problem

**Comment by gibbsmaya** [comment]
LGTM

**Comment by gibbsmaya** [comment]
Marking as done, but assigning to Erin for code review.

**Comment by gibbsmaya** [comment]
@todd-dembrey please can you deploy this to test?

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah

This work is now ready for testing. This work consists of the new statuses for the workflow states an application goes through for what the applicant sees. This is best seen from the status bar on the application page and also the status bar on the applicant's dashboard:
![screen shot 2019-01-22 at 09 10 23](https://user-images.githubusercontent.com/19690895/51524258-94c3e480-1e25-11e9-91e0-cbdce58c25f0.png)
You will see that labels have been updated as well as some additional new states as discussed in the demo call. As a brief summary, the statuses mean the following:

**2 stage workflow (concept note and proposal)**

 - Concept note received: maps to the screening phase in OTF statuses
 - OTF review: maps to internal review, ready for discussion and ready for preliminary determination in OTF statuses. No update to applicant between these OTF statuses.
 - Preliminary decision: A signal to the applicant that there is a decision point here. Maps to the decision being made by OTF to either invite to proposal or dismiss. - Invited for proposal: Applicant has been invited for proposal bit has not yet submitted proposal.
 - Invited to proposal: maps directly to invited for proposal in OTF statuses
 - Proposal received: maps directly to proposal received in OTF statuses
 - OTF review: maps to internal review and ready for discussion in OTF statuses. No update to applicant between these OTF statuses.
 - Advisory council review: maps to Advisory council review, ready for discussion and ready for final determination in OTF statuses. No update to applicant between these OTF statuses.
 - Application outcome: Maps to final determination in OTF statuses - either dismissed or accepted.

Please can you test both types of application and ensure you are happy with the states? As mentioned in #792 I suggest testing this alongside that issue as they are interdependent, reviewing what the applicant sees for each OTF status update. 

Please test this against the acceptance criteria noted in the initial issue description.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Remember that it is really easy for us to change the labelling on the status names so let us know if any of these don't make sense.

Thanks,
Maya

**Comment by danblah** [comment]
Looks good, acceptance criteria met from my testing. What effects does this have on single stage applications, both w/external and w/o external review?

**Comment by gibbsmaya** [comment]
Single stage applications would follow the same logic and workflow states - so like a concept note for a single stage with only OTF review (but the final state would be final determination rather than preliminary determination, and with additional states for advisory council review for workflows with external review. All would follow same format. Please do test this case too and ensure you are happy with it.

**Comment by gibbsmaya** [comment]
@danblah @fourthletter can you confirm if you are happy for this to me moved into production deployment?

**Comment by fourthletter** [comment]
All acceptance criteria are visible and functional during today's test. Thanks! 💥

**Comment by gibbsmaya** [comment]
Ready for deployment to production
