### ISSUE TITLE
Batch action: status

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#858]
Batch actions will allow OTF staff to apply the same action to multiple submissions at the same time via the listing table. 

**Acceptance criteria**

- [x] When at least one submission row is selected using the checkbox, a 'Update status' action appears 
- [x] Batch Status changes can only be applied to submissions in statuses that allow the same actions. The button will be disabled otherwise.
- [x] Clicking on an action will show similar interface as used for the current Update status  functionality on the individual submission page but with extra context about the submissions selected (number of submissions and expand link to see submission titles) to clarify that this is a batch action. Design: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/342781107
- [x] On batch action submit, page refreshes, batch selections are unselected and message displayed to user confirming action (design of message as per https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971429 but no undo!)
- [x] If error when batch updating display message to user (same design as per action confirmation at top of screen)
- [x] Batch actions available on all submission tables on All Submissions page, Submissions by Round page and Submission by Status page (not submission summary blocks on dashboard or submission overview page)
- [x] Users will have the same permissions to perform changes as they do currently
- [x] Email notifications are unaffected: Applicants will each receive emails as if an action had been taken on their submission only
- [x] Activity feed entries are unaffected: Submissions will have an activity added, it will not be tracked as a batch action 
- [x] Slack notifications updated: only one notification is sent to handle batch message e.g. `“<user> has done <action> to: <submission1><submission2><submission3>”`

Design (batch actions): https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971996
Design (Change status modal): https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/342781107

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by emullaney** [comment]
I'm seeing a few problems and I'm wondering whether they are related to my webpack issues. I do have `gulp watch:app` successfully running after changing [webpack.prod.config.js](https://github.com/OpenTechFund/opentech.fund/blob/7b49da51dcc08407abf3d9a9a94b29fadb849a2b/opentech/static_src/src/app/webpack.prod.config.js#L9) locally, and running npm install first. But I can't seem to update via the batch screen. 

I tried to selected two submissions and clicked on "Status", but when I opened the window, they didn't show up in the hide/expand.
![image](https://user-images.githubusercontent.com/11393311/53016616-00e13a80-341c-11e9-9770-c8a1ea312703.png)

And then, I saw this form error which we should never see but it's definitely related to the above issue.
![image](https://user-images.githubusercontent.com/11393311/53016557-e14a1200-341b-11e9-908d-f38d529b79ee.png)

In this case, nothing was updated, I didn't see any messages of failure, aside from this form error that I don't think is intentional. I think something is off in the javascript. I spent a little time trying to debug it but couldn't find any obvious issues.

**Comment by todd-dembrey** [comment]
@gibbsmaya This is now on dev. I have changed the acceptance criteria for when the options are enabled.

I have allowed you to select submissions in a variety of states that have the same action. This was the easiest approach, but could be extended to limit based on having the same status of the application.

I only came across one instance where this was confusing. On the all submissions page - trying to move several things into "ready for determination" didnt work because one of the selected was requiring "ready for preliminary determination".

**Comment by gibbsmaya** [comment]
@todd-dembrey this sounds fine, have updated AC above to reflect. A couple of point below:

 - [ ] No confirmation message to user on batch submit - there should be
 - [ ] More information requested - assuming this behaviour will be updated in #859 ?

**Comment by todd-dembrey** [comment]
a) ah yes, good spot. 
b) yes, any determination behaviour is coming in #859 - you can currently progress but are nor forced to determine.

**Comment by todd-dembrey** [comment]
@gibbsmaya This is now deployed to dev. Too many messages to notice i missed the main one!

If you want to test the error. do a batch actions on a submission after changing its status on a detail page without having refreshed the listing view.

**Comment by gibbsmaya** [comment]
Confirmation message now working.

I did try to test the error in that way - but got a 500 error when doing the batch submission - assuming that is not the error we are looking for ;) It was doing a batch update on submissions 20, 19 and 1. Submission 1 is the problem submission that should have caused the error.

**Comment by todd-dembrey** [comment]
It was an issue with how i was getting data about the submissions that should have worked. I've made that more robust and it is deploying to dev.

**Comment by gibbsmaya** [comment]
LGTM. Thanks.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah, @arduina, 

This work is now ready for testing. This work is adding a batch action for updating the status of submissions. You can access this on the all submissions page at https://test-apply.opentech.fund/apply/submissions/all/. Note that batch determine actions (accept/dismiss/invite to proposal will be added in #859 and deployed next week)

Please test this against the acceptance criteria noted in the initial issue description where you will also see a link to the design.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
All acceptance criteria are visible and functional. Thank you! 500 TARDIS miles!

**Comment by gibbsmaya** [comment]
Thanks @fourthletter. Assigning to @todd-dembrey ready for deployment to live.
