### ISSUE TITLE
Red Team application option is not rendering correctly

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#996]
See https://apply.opentech.fund/apply/submissions/3671/, where the selected "What services are you seeking support for?" is showing up as a series of bullets rather than a single selected option.

**Comment by todd-dembrey** [comment]
It looks like the category serializer is not working correctly. it isn't returning a question

![image](https://user-images.githubusercontent.com/6338661/52631805-adb93600-2eb7-11e9-921a-59d2f2df05d6.png)

I think this is because the field label is optional 
https://github.com/OpenTechFund/opentech.fund/blob/3187b9d201c88ed495ffb1ecb42336847a1b52d4/opentech/apply/categories/blocks.py#L30-L33

We shoudl be using the values like the normal field 
https://github.com/OpenTechFund/opentech.fund/blob/master/opentech/apply/categories/blocks.py#L48

To pass to the serialize method.
https://github.com/OpenTechFund/opentech.fund/blob/3187b9d201c88ed495ffb1ecb42336847a1b52d4/opentech/apply/stream_forms/blocks.py#L54-L59

See also checkboxes, which is returning a string of the value rather than an array:
![image](https://user-images.githubusercontent.com/6338661/52631852-ce818b80-2eb7-11e9-832a-78b33008213d.png)

This needs a `prepare_data` method which iterates over the array (remember to test this on the submissions detail page.

```
def prepare_data(self, value, data, serialize=False):
         return [super().prepare_data(value, item, serialize) for item in data]
```

**Comment by danblah** [comment]
Thanks for the quick fix!

**Comment by todd-dembrey** [comment]
@danblah Those are just some dev notes. I haven't made the fix yet. Reopening because this still needs fixing.

**Comment by danblah** [comment]
Apologies, crossed wires on the other hotfix.
